# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ideia à Vista
email: flamenco.bluegrass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Uma produtora de cinema e games.
author: Tobias B. Ulrich
baseurl: "/ideiaavista2/" # the subpath of your site, e.g. /blog
url: "https://tobiasbu.github.io" #"https://ideiaavista.com.br" #"http://ideiaavista.com.br" # the base hostname & protocol for your site

repository: "tobiasbu/ideiaavista2"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true
  startings: [html, head, body]

exclude: ['.sass-cache','_css','_includes','_backup', '_sections','deploy.js', 'README.md', 'Gemfile','Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js']
